<a href="https://colab.research.google.com/github/PerlaLunaD/csv-py/blob/master/An%C3%A1lisis__Salarial__por__Industria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. El problema del negocio

Como afecta el grado academico y la especializacion al salario en diferenrtes tipos de trabajo dentro de una industria en especifico.

2. Importando librerias necesarias

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

3. Carga y exploracion de datos (una primer mirada al dataset)

In [22]:
data = pd.read_csv ('/content/train_features.csv')

In [23]:
print(data.shape)

(1000000, 10)

In [24]:
data.head()

,jobId,companyId,jobType,degree,major,industry,yearsExperience,milesFromMetropolis,Unnamed: 8,salary
0,JOB1362684407687,COMP37,CFO,MASTERS,MATH,HEALTH,10,83,NaN,130
1,JOB1362684407688,COMP19,CEO,HIGH_SCHOOL,NONE,WEB,3,73,NaN,101
2,JOB1362684407689,COMP52,VICE_PRESIDENT,DOCTORAL,PHYSICS,HEALTH,10,38,NaN,137
3,JOB1362684407690,COMP38,MANAGER,DOCTORAL,CHEMISTRY,AUTO,8,17,NaN,142
4,JOB1362684407691,COMP7,VICE_PRESIDENT,BACHELORS,PHYSICS,FINANCE,8,16,NaN,163

In [25]:
data.tail()

,jobId,companyId,jobType,degree,major,industry,yearsExperience,milesFromMetropolis,Unnamed: 8,salary
999995,JOB1362685407682,COMP56,VICE_PRESIDENT,BACHELORS,CHEMISTRY,HEALTH,19,94,NaN,88
999996,JOB1362685407683,COMP24,CTO,HIGH_SCHOOL,NONE,FINANCE,12,35,NaN,160
999997,JOB1362685407684,COMP23,JUNIOR,HIGH_SCHOOL,NONE,EDUCATION,16,81,NaN,64
999998,JOB1362685407685,COMP3,CFO,MASTERS,NONE,HEALTH,6,5,NaN,149
999999,JOB1362685407686,COMP59,JUNIOR,BACHELORS,NONE,EDUCATION,20,11,NaN,88

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   jobId                1000000 non-null  object
 1   companyId            1000000 non-null  object
 2   jobType              1000000 non-null  object
 3   degree               1000000 non-null  object
 4   major                1000000 non-null  object
 5   industry             1000000 non-null  object
 6   yearsExperience      1000000 non-null  int64
 7   milesFromMetropolis  1000000 non-null  int64
 8   Unnamed: 8           0 non-null        float64
 9   salary               1000000 non-null  int64
dtypes: float64(1), int64(3), object(6)
memory usage: 76.3+ MB

In [27]:
data.count()

jobId                  1000000
companyId              1000000
jobType                1000000
degree                 1000000
major                  1000000
industry               1000000
yearsExperience        1000000
milesFromMetropolis    1000000
Unnamed: 8                   0
salary                 1000000
dtype: int64

In [28]:
cols =['jobId','companyId','jobType','degree','major','industry','yearsExperience','milesFromMetropolis', 'Unnamed: 8', 'salary']

df = data[cols]

In [29]:
df = data[cols]

In [31]:
df

,jobId,companyId,jobType,degree,major,industry,yearsExperience,milesFromMetropolis,Unnamed: 8,salary
0,JOB1362684407687,COMP37,cfo,masters,MATH,health,10,83,NaN,130
1,JOB1362684407688,COMP19,ceo,high_school,NONE,web,3,73,NaN,101
2,JOB1362684407689,COMP52,vice_president,doctoral,PHYSICS,health,10,38,NaN,137
3,JOB1362684407690,COMP38,manager,doctoral,CHEMISTRY,auto,8,17,NaN,142
4,JOB1362684407691,COMP7,vice_president,bachelors,PHYSICS,finance,8,16,NaN,163
...,...,...,...,...,...,...,...,...,...,...
999995,JOB1362685407682,COMP56,vice_president,bachelors,CHEMISTRY,health,19,94,NaN,88
999996,JOB1362685407683,COMP24,cto,high_school,NONE,finance,12,35,NaN,160
999997,JOB1362685407684,COMP23,junior,high_school,NONE,education,16,81,NaN,64
999998,JOB1362685407685,COMP3,cfo,masters,NONE,health,6,5,NaN,149
999999,JOB1362685407686,COMP59,junior,bachelors,NONE,education,20,11,NaN,88

In [36]:
df.rename(columns={'jobId':'Id'},inplace=True)
df.rename(columns={'companyId':'CompanyId'},inplace=True)
df.rename(columns={'jobType':'JobType'},inplace=True)
df.rename(columns={'yearsExperience	':'YearsExperience	'},inplace=True)
df.rename(columns={'milesFromMetropolis':'MilesFromMetropolis'},inplace=True)
df.rename(columns={'Unnamed: 8':'Unnamed'},inplace=True)

In [37]:
df

,Id,CompanyId,JobType,degree,major,industry,yearsExperience,MilesFromMetropolis,Unnamed,salary
0,JOB1362684407687,COMP37,cfo,masters,MATH,health,10,83,NaN,130
1,JOB1362684407688,COMP19,ceo,high_school,NONE,web,3,73,NaN,101
2,JOB1362684407689,COMP52,vice_president,doctoral,PHYSICS,health,10,38,NaN,137
3,JOB1362684407690,COMP38,manager,doctoral,CHEMISTRY,auto,8,17,NaN,142
4,JOB1362684407691,COMP7,vice_president,bachelors,PHYSICS,finance,8,16,NaN,163
...,...,...,...,...,...,...,...,...,...,...
999995,JOB1362685407682,COMP56,vice_president,bachelors,CHEMISTRY,health,19,94,NaN,88
999996,JOB1362685407683,COMP24,cto,high_school,NONE,finance,12,35,NaN,160
999997,JOB1362685407684,COMP23,junior,high_school,NONE,education,16,81,NaN,64
999998,JOB1362685407685,COMP3,cfo,masters,NONE,health,6,5,NaN,149
999999,JOB1362685407686,COMP59,junior,bachelors,NONE,education,20,11,NaN,88